packageExtensions:
  argon2@*:
    dependencies:
      node-gyp: ^9.0.0
  babel-plugin-relay@*:
    dependencies:
      "@babel/runtime": ^7.18.0

yarnPath: .yarn/releases/yarn-4.0.0-rc.15.cjs

nodeLinker: pnp
